go_binary(
    name = "main",
    srcs = ["buildifier.go"],
    deps = [
        "//build",
        "//buildifier/utils",
        "//differ",
        "//tables",
        "//warn",
        "//wspace",
    ],
)
