go_library(
    name = "labels",
    srcs = ["labels.go"],
    visibility = [
        "//edit:all",
        "//unused_deps:all",
    ],
)

go_test(
    name = "labels_test",
    srcs = ["labels_test.go"],
    deps = [":labels"],
)
