go_library(
    name = "extra_actions_base_proto",
    srcs = ["extra_actions_base.gen.pb.go"],
    visibility = ["//unused_deps:all"],
    deps = [
        "///third_party/go/google.golang.org_protobuf//reflect/protoreflect",
        "///third_party/go/google.golang.org_protobuf//runtime/protoimpl",
    ],
)
