go_library(
    name = "api_proto",
    srcs = ["api.gen.pb.go"],
    visibility = ["//edit:all"],
    deps = [
        "///third_party/go/google.golang.org_protobuf//reflect/protoreflect",
        "///third_party/go/google.golang.org_protobuf//runtime/protoimpl",
    ],
)
