go_binary(
    name = "main",
    srcs = [
        "jar_manifest.go",
        "unused_deps.go",
    ],
    deps = [
        "///third_party/go/github.com_golang_protobuf//proto",
        "//build",
        "//config",
        "//deps_proto",
        "//edit",
        "//extra_actions_base_proto",
        "//labels",
    ],
)
