go_library(
    name = "convertast",
    srcs = ["convert_ast.go"],
    visibility = ["//buildifier2:all"],
    deps = [
        "///third_party/go/go.starlark.net//syntax",
        "//build",
    ],
)
