go_library(
    name = "deps_proto",
    srcs = ["deps.gen.pb.go"],
    visibility = ["//unused_deps:all"],
    deps = [
        "///third_party/go/google.golang.org_protobuf//reflect/protoreflect",
        "///third_party/go/google.golang.org_protobuf//runtime/protoimpl",
    ],
)
